<script setup lang="ts">
import { onMounted, onUnmounted, ref } from 'vue'
import AppState from '../../components/AppState.vue'
import UiButton from '../../components/UiButton.vue'
import { api } from '../../lib/api'
const jobs=ref<any[]>([]);const state=ref<'loading'|'loaded'|'error'>('loading');const filter=ref('');let timer:number|undefined
async function load(){try{const query=filter.value?`?status=${filter.value}`:'';jobs.value=(await api<any>(`/api/v1/admin/jobs${query}`)).jobs;state.value='loaded'}catch{state.value='error'}}
async function retry(id:number){await api(`/api/v1/admin/jobs/${id}/retry`,{method:'POST'});await load()}
async function cancel(id:number){await api(`/api/v1/admin/jobs/${id}/cancel`,{method:'POST'});await load()}
onMounted(()=>{void load();timer=window.setInterval(()=>{if(jobs.value.some(job=>['queued','running'].includes(job.status)))void load()},2000)});onUnmounted(()=>window.clearInterval(timer))
</script>
<template><div><header class="page-header"><p class="eyebrow">Trabalho em segundo plano</p><h1>Jobs</h1><p>Histórico real de scans, reinícios e falhas acionáveis.</p></header><label class="filter-field" for="job-filter">Status <select id="job-filter" v-model="filter" @change="load"><option value="">Todos</option><option value="queued">Na fila</option><option value="running">Executando</option><option value="completed">Concluídos</option><option value="failed">Falhos</option><option value="cancelled">Cancelados</option></select></label><AppState v-if="state==='loading'" kind="loading" /><AppState v-else-if="state==='error'" kind="error" title="Não foi possível carregar os jobs"><button class="button button--secondary" @click="load">Tentar novamente</button></AppState><section v-else class="admin-list"><article v-for="job in jobs" :key="job.id"><div><h2>Scan · {{ job.libraryName }}</h2><p>{{ job.status }} · tentativa {{ job.attempt }}/{{ job.maxAttempts }} · {{ new Date(job.queuedAt+'Z').toLocaleString() }}</p><p v-if="job.summary">{{ job.summary.added }} adicionados · {{ job.summary.updated }} alterados · {{ job.summary.renamed }} renomeados · {{ job.summary.missing }} ausentes · {{ job.summary.errors.length }} falhos</p><p v-if="job.error" class="field__error">{{ job.error }}</p></div><div class="reader-actions"><UiButton v-if="job.status==='failed'" @click="retry(job.id)">Tentar novamente</UiButton><UiButton v-if="job.status==='queued'" variant="danger" @click="cancel(job.id)">Cancelar</UiButton></div></article><AppState v-if="!jobs.length" kind="empty" title="Nenhum job neste estado" message="Novos scans aparecerão aqui." /></section></div></template>
