<script setup lang="ts">
import { onMounted, ref } from 'vue'; import { useRoute } from 'vue-router'; import AppState from '../../components/AppState.vue'; import UiButton from '../../components/UiButton.vue'; import UiField from '../../components/UiField.vue'; import { api } from '../../lib/api'
const route=useRoute();const id=Number(route.params.id);const library=ref<any>();const errors=ref<any[]>([]);const name=ref('');const libraryPath=ref('');const rescanIntervalMinutes=ref(0);const loading=ref(true);const busy=ref(false);const error=ref('');const notice=ref('')
async function load(){loading.value=true;try{const list=(await api<{libraries:any[]}>('/api/v1/admin/libraries')).libraries;library.value=list.find(item=>item.id===id);if(!library.value)throw new Error('Biblioteca não encontrada.');name.value=library.value.name;libraryPath.value=library.value.path;rescanIntervalMinutes.value=library.value.rescanIntervalMinutes||0;errors.value=(await api<{errors:any[]}>(`/api/v1/admin/libraries/${id}/errors`)).errors;error.value=''}catch(reason){error.value=reason instanceof Error?reason.message:'Falha ao carregar.'}finally{loading.value=false}}
async function save(){try{await api(`/api/v1/admin/libraries/${id}`,{method:'PUT',body:JSON.stringify({name:name.value,path:libraryPath.value,rescanIntervalMinutes:rescanIntervalMinutes.value})});notice.value='Biblioteca atualizada.';await load()}catch(reason){error.value=reason instanceof Error?reason.message:'Falha ao salvar.'}}
async function scan(){busy.value=true;try{const result=await api<{job:any}>(`/api/v1/admin/libraries/${id}/scan?async=true`,{method:'POST'});notice.value=`Scan #${result.job.id} entrou na fila. Acompanhe o relatório em Jobs.`;await load()}catch(reason){error.value=reason instanceof Error?reason.message:'Falha no scan.'}finally{busy.value=false}}
onMounted(load)
</script>
<template><div><RouterLink to="/admin/libraries">← Bibliotecas</RouterLink><AppState v-if="loading" kind="loading" /><AppState v-else-if="error&&!library" kind="error" title="Biblioteca indisponível" :message="error" /><template v-else><header class="page-header"><p class="eyebrow">Biblioteca montada</p><h1>{{ library.name }}</h1><p><code>{{ library.path }}</code></p></header><p v-if="notice" class="alert alert--success" role="status">{{ notice }}</p><p v-if="error" class="alert alert--error" role="alert">{{ error }}</p><div class="stat-grid"><div><strong>{{ library.bookCount }}</strong><span>Livros</span></div><div><strong>{{ library.errorCount||0 }}</strong><span>Erros</span></div><div><strong>{{ library.last_scan_status||'Nunca' }}</strong><span>Último status</span></div></div><section class="settings-section"><h2>Configuração</h2><form class="form-row form-row--library" @submit.prevent="save"><UiField label="Nome" for-id="detail-name"><input id="detail-name" v-model="name" required /></UiField><UiField label="Caminho" for-id="detail-path"><input id="detail-path" v-model="libraryPath" required /></UiField><UiField label="Reescaneamento automático" for-id="detail-rescan"><select id="detail-rescan" v-model.number="rescanIntervalMinutes"><option :value="0">Somente manual</option><option :value="15">A cada 15 minutos</option><option :value="60">A cada hora</option><option :value="360">A cada 6 horas</option><option :value="1440">Diariamente</option><option :value="10080">Semanalmente</option></select></UiField><UiButton type="submit" variant="primary">Salvar alterações</UiButton></form><UiButton :disabled="busy" @click="scan">{{ busy?'Escaneando…':'Escanear agora' }}</UiButton></section><section class="settings-section"><h2>Problemas de ingestão</h2><ul v-if="errors.length" class="error-list"><li v-for="item in errors" :key="item.file"><code>{{ item.file }}</code><span>{{ item.message }}</span></li></ul><p v-else>Nenhum problema de ingestão.</p></section></template></div></template>
