<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import AppState from '../../components/AppState.vue'
import UiButton from '../../components/UiButton.vue'
import UiField from '../../components/UiField.vue'
import UiDialog from '../../components/UiDialog.vue'
import { api } from '../../lib/api'

const users = ref<any[]>([]); const libraries = ref<any[]>([]); const loading = ref(true); const error = ref(''); const notice = ref(''); const showCreate = ref(false)
const form = reactive({ username: '', displayName: '', password: '', role: 'reader', libraryIds: [] as number[] })
async function load(){loading.value=true;try{const [userResult,libraryResult]=await Promise.all([api<any>('/api/v1/admin/users'),api<any>('/api/v1/admin/libraries')]);users.value=userResult.users;libraries.value=libraryResult.libraries;error.value=''}catch(reason){error.value=reason instanceof Error?reason.message:'Falha ao carregar.'}finally{loading.value=false}}
async function create(){try{await api('/api/v1/admin/users',{method:'POST',body:JSON.stringify(form)});Object.assign(form,{username:'',displayName:'',password:'',role:'reader',libraryIds:[]});showCreate.value=false;notice.value='Usuário criado.';await load()}catch(reason){error.value=reason instanceof Error?reason.message:'Falha ao criar usuário.'}}
async function setActive(user:any){try{await api(`/api/v1/admin/users/${user.id}`,{method:'PUT',body:JSON.stringify({active:!user.active})});notice.value=user.active?'Usuário desativado e sessões revogadas.':'Usuário reativado.';await load()}catch(reason){error.value=reason instanceof Error?reason.message:'Falha ao atualizar usuário.'}}
function edit(user:any){user.editing=!user.editing;user.editRole=user.role;user.editLibraryIds=[...user.libraryIds];user.newPassword=''}
async function saveUser(user:any){try{await api(`/api/v1/admin/users/${user.id}`,{method:'PUT',body:JSON.stringify({role:user.editRole,libraryIds:user.editLibraryIds,...(user.newPassword?{password:user.newPassword}:{})})});notice.value='Acesso atualizado; uma nova senha revoga as sessões existentes.';await load()}catch(reason){error.value=reason instanceof Error?reason.message:'Falha ao atualizar acesso.'}}
onMounted(load)
</script>

<template><div><header class="page-header"><p class="eyebrow">Acesso e privacidade</p><h1>Usuários</h1><p>Contas de leitura têm progresso próprio e acesso somente às bibliotecas selecionadas.</p><UiButton variant="primary" @click="showCreate=true">Adicionar usuário</UiButton></header><p v-if="notice" class="alert alert--success" role="status">{{ notice }}</p><p v-if="error" class="alert alert--error" role="alert">{{ error }}</p><UiDialog :open="showCreate" title="Adicionar usuário" @close="showCreate=false"><form class="user-form" @submit.prevent="create"><UiField label="Usuário" for-id="user-name"><input id="user-name" v-model="form.username" autofocus required autocomplete="off" /></UiField><UiField label="Nome exibido" for-id="display-name"><input id="display-name" v-model="form.displayName" required /></UiField><UiField label="Senha inicial" for-id="initial-password" hint="Mínimo de 12 caracteres."><input id="initial-password" v-model="form.password" type="password" minlength="12" required autocomplete="new-password" /></UiField><UiField label="Função" for-id="user-role"><select id="user-role" v-model="form.role"><option value="reader">Leitor</option><option value="admin">Administrador</option></select></UiField><fieldset v-if="form.role==='reader'" class="library-access"><legend>Bibliotecas liberadas</legend><label v-for="library in libraries" :key="library.id"><input v-model="form.libraryIds" type="checkbox" :value="library.id" /> {{ library.name }}</label></fieldset><UiButton type="submit" variant="primary">Criar usuário</UiButton></form></UiDialog><AppState v-if="loading" kind="loading" /><section v-else class="admin-list" aria-label="Usuários"><article v-for="user in users" :key="user.id"><div class="user-entry"><h2>{{ user.displayName }}</h2><p>@{{ user.username }} · {{ user.role==='admin'?'Administrador':'Leitor' }} · {{ user.active?'Ativo':'Desativado' }}</p><p v-if="user.role==='reader'">{{ user.libraryIds.length }} biblioteca(s) liberada(s)</p><form v-if="user.editing" class="user-edit" @submit.prevent="saveUser(user)"><label>Função<select v-model="user.editRole"><option value="reader">Leitor</option><option value="admin">Administrador</option></select></label><fieldset v-if="user.editRole==='reader'" class="library-access"><legend>Bibliotecas liberadas</legend><label v-for="library in libraries" :key="library.id"><input v-model="user.editLibraryIds" type="checkbox" :value="library.id" /> {{ library.name }}</label></fieldset><label>Nova senha opcional<input v-model="user.newPassword" type="password" minlength="12" autocomplete="new-password" /></label><UiButton type="submit" variant="primary">Salvar acesso</UiButton></form></div><div class="reader-actions"><UiButton @click="edit(user)">{{ user.editing?'Cancelar':'Gerenciar' }}</UiButton><UiButton :variant="user.active?'danger':'secondary'" @click="setActive(user)">{{ user.active?'Desativar':'Reativar' }}</UiButton></div></article></section></div></template>
